### ISSUE TITLE
Better name

### ISSUE THREAD

**Issue by kesla** [micnews/image-cropper#5]
Hey ya'll

What should this be named? Basically it's a frontend widget to crop images in vanilla js. It'll eventually be open source and put on npm.

`image-cropper`is free on npm, but perhaps it's a bit too generic? Maybe `image-cropper-widget` is beter? What do you think?

**Comment by kesla** [comment]
ping @hij1nx @juliangruber @ralphtheninja @daedelus-j

**Comment by heapwolf** [comment]
I'm a huge fan of self describing names, even if they are generic names.

On Sunday, September 28, 2014, David Björklund notifications@github.com
wrote:

> ping @hij1nx https://github.com/hij1nx @juliangruber
> https://github.com/juliangruber @ralphtheninja
> https://github.com/ralphtheninja @daedelus-j
> https://github.com/daedelus-j
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/micnews/image-cropper/issues/5#issuecomment-57088715.

## 

## 

Paolo Fragomeni
Founder, Here is How
http://hereishow.to

github.com/hij1nx
twitter.com/hij1nx

**Comment by kesla** [comment]
@hij1nx So am I, so my question here is perhaps mostly if we should add the `-widget` postfix or not...

**Comment by heapwolf** [comment]
Hmmm... No for brevity? :)

On Sunday, September 28, 2014, David Björklund notifications@github.com
wrote:

> @hij1nx https://github.com/hij1nx So am I, so my question here is
> perhaps mostly if we should add the -widget postfix or not...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/micnews/image-cropper/issues/5#issuecomment-57089279.

## 

## 

Paolo Fragomeni
Founder, Here is How
http://hereishow.to

github.com/hij1nx
twitter.com/hij1nx

**Comment by ralphtheninja** [comment]
I think `image-cropper` is fine. Use the README to clarify the rest :)

**Comment by kesla** [comment]
thanks Magnus & Paolo. You're the best.

**Comment by ralphtheninja** [comment]
:heart:
